#!/bin/bash
# Build a native acceptance harness for the CVODE bytecode verifier and evaluator.
#
# The harness does NOT re-implement either function. It slices both source
# sections straight out of wasm-sundials/cvode_wrapper.c and includes them, so
# tests exercise the exact C text that ships in WASM. Re-run this script after
# changing either section.
#
# Usage: generate_native_harness.sh [cc]
set -euo pipefail

CC="${1:-cc}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../../../.." && pwd)"
WRAPPER="$REPO/wasm-sundials/cvode_wrapper.c"
INC="$HERE/verifier_under_test.inc"
BIN="$HERE/verify_bytecode_native"

if [ ! -f "$WRAPPER" ]; then
  echo "error: cannot find $WRAPPER" >&2
  exit 1
fi

# Extract the verifier and evaluator verbatim from the wrapper, so native
# acceptance tests exercise the same validation and interpreter source as WASM.
START=$(grep -n '^// ---- Load-time bytecode verification ----$' "$WRAPPER" | cut -d: -f1)
END=$(grep -n '^// ---- Network Bytecode API ----$' "$WRAPPER" | cut -d: -f1)
EVAL_START=$(grep -n '^static double evaluate_expression' "$WRAPPER" | cut -d: -f1)
EVAL_END=$(grep -n '^// Compute all observables$' "$WRAPPER" | cut -d: -f1)

if [ -z "$START" ] || [ -z "$END" ] || [ -z "$EVAL_START" ] || [ -z "$EVAL_END" ]; then
  echo "error: could not locate verifier/evaluator sections in $WRAPPER" >&2
  exit 1
fi

{
  echo "// GENERATED by packages/engine/tests/native/generate_native_harness.sh"
  echo "// Verbatim verifier slice: cvode_wrapper.c lines ${START}-$((END-1))."
  echo "// Verbatim evaluator slice: cvode_wrapper.c lines ${EVAL_START}-$((EVAL_END-1))."
  echo "// Do not edit; edit cvode_wrapper.c and re-run this script."
  echo ""
  echo "#include <math.h>"
  echo "#include <stdarg.h>"
  echo "#include <stdint.h>"
  echo ""
  echo "#define BC_STACK_MAX 64"
  echo ""
  sed -n "${START},$((END-1))p" "$WRAPPER"
  echo ""
  sed -n "${EVAL_START},$((EVAL_END-1))p" "$WRAPPER"
} > "$INC"

"$CC" -std=c11 -O1 -g \
  -fsanitize=address,undefined \
  -fno-omit-frame-pointer \
  -Wall -Wno-macro-redefined \
  -o "$BIN" "$HERE/verify_bytecode_native.c" -lm

echo "built $BIN against cvode_wrapper.c lines ${START}-$((END-1))"