import type { BNGLModel, BNGLReaction } from '../../types';
import type { ExpandedNetwork } from '../../interfaces/SimulationEngine';

/**
 * Configuration options for MATLAB .m file generation.
 * Mirrors Perl BNG2 writeMfile and C++ MatlabWriter::Options.
 */
export interface MatlabWriterOptions {
  /** Start time (default 0) */
  tStart?: number;
  /** End time (default 10) */
  tEnd?: number;
  /** Number of output steps (default 100) */
  nSteps?: number;
  /** Relative tolerance (default 1e-8) */
  rtol?: number;
  /** Absolute tolerance (default 1e-8) */
  atol?: number;
  /** Enable solver stats output (default true) */
  stats?: boolean;
  /** Use BDF method (default false) */
  bdf?: boolean;
  /** Maximum BDF order (default 5) */
  maxOrder?: number;
  /** Maximum step size (0 = unlimited) */
  maxStep?: number;
}

/**
 * Represents a single observable group with its species-weight map.
 */
interface ObservableGroup {
  name: string;
  entries: Array<{ speciesIndex: number; weight: number }>;
}

/**
 * Stoichiometry entry: maps a species to its net coefficient for each reaction.
 */
interface StoichEntry {
  speciesIndex: number;
  rxnCoeffs: Array<{ rxnIndex: number; coeff: number }>;
}

/**
 * MatlabWriter generates a self-contained MATLAB .m file that runs an ODE
 * simulation using ode15s. Output format matches Perl BNG2's writeMfile
 * and the C++ MatlabWriter.
 *
 * The generated file contains:
 * - Main function with signature:
 *     function [err, timepoints, species_out, observables_out] = name(timepoints, species_init, parameters, suppress_plot)
 * - Nested helper functions: getDefaultParameters, getInitialSpecies,
 *   calc_expressions, calc_observables, calc_ratelaws, calc_species_deriv
 */
export class MatlabWriter {
  /**
   * Generate a valid MATLAB function name from a model name.
   * Non-alphanumeric characters become underscores; leading digits get a prefix.
   */
  static makeMatlabFunctionName(modelName: string): string {
    let name = modelName.replace(/[^A-Za-z0-9]/g, '_');
    if (name.length > 0 && /^[0-9]/.test(name)) {
      name = 'model_' + name;
    }
    return name || 'bng_model';
  }

  /**
   * Write a complete MATLAB .m file string.
   *
   * @param model   - The parsed BNGL model (species, parameters, observables, reactions).
   * @param network - Optional expanded network. When provided, uses its concrete
   *                  species and reactions; otherwise falls back to model arrays.
   * @param opts    - Solver and output options.
   * @returns The complete .m file as a string.
   */
  static write(
    model: BNGLModel,
    network?: ExpandedNetwork | null,
    opts: MatlabWriterOptions = {},
  ): string {
    const tStart = opts.tStart ?? 0;
    const tEnd = opts.tEnd ?? 10;
    const nSteps = opts.nSteps ?? 100;
    const rtol = opts.rtol ?? 1e-8;
    const atol = opts.atol ?? 1e-8;
    const stats = opts.stats ?? true;
    const bdf = opts.bdf ?? false;
    const maxOrder = opts.maxOrder ?? 5;
    const maxStep = opts.maxStep ?? 0;

    const funcName = this.makeMatlabFunctionName(model.name || 'model');

    // Resolve species and reactions from network or model
    const species = network?.species ?? model.species ?? [];
    const reactions = network?.reactions ?? model.reactions ?? [];
    const nSpecies = species.length;
    const nRxns = reactions.length;

    // Collect parameters
    const paramNames: string[] = [];
    const paramValues: number[] = [];
    const params = model.parameters ?? {};
    for (const [name, value] of Object.entries(params)) {
      paramNames.push(name);
      paramValues.push(value);
    }

    // Build observable groups
    const groups = this.computeObservableGroups(model, species);

    // Compute stoichiometry
    const stoich = this.computeStoichiometryFromSpecies(reactions, species);

    // Detect fixed (constant) species
    const fixedSpecies: boolean[] = species.map(s => s.isConstant === true);

    // Build the .m file
    const m: string[] = [];

    // Function header
    m.push(`function [err, timepoints, species_out, observables_out] = ${funcName}(timepoints, species_init, parameters, suppress_plot)`);
    m.push(`%% ${funcName} - MATLAB ODE model`);
    m.push(`%% Generated by BioNetGen TypeScript Engine`);
    m.push(`%%`);
    m.push(`%% Usage:`);
    m.push(`%%   [err, timepoints, species_out, observables_out] = ${funcName}()`);
    m.push(`%%   [err, timepoints, species_out, observables_out] = ${funcName}(timepoints, species_init, parameters)`);
    m.push('');

    // Default input handling
    m.push('%% Default parameters, initial conditions, and calculation handlers');
    m.push('if (nargin < 1)');
    m.push(`    timepoints = linspace(${tStart}, ${tEnd}, ${nSteps + 1})';`);
    m.push('end');
    m.push('if (nargin < 2)');
    m.push('    species_init = getInitialSpecies();');
    m.push('end');
    m.push('if (nargin < 3)');
    m.push('    parameters = getDefaultParameters();');
    m.push('end');
    m.push('if (nargin < 4)');
    m.push('    suppress_plot = 0;');
    m.push('end');
    m.push('');

    // Validate dimensions
    m.push('%% Validate input dimensions');
    m.push(`if (length(parameters) ~= ${paramNames.length})`);
    m.push(`    error('parameters must have ${paramNames.length} elements');`);
    m.push('end');
    m.push(`if (length(species_init) ~= ${nSpecies})`);
    m.push(`    error('species_init must have ${nSpecies} elements');`);
    m.push('end');
    m.push('');

    // Model dimensions
    m.push('%% Model dimensions');
    m.push(`n_species = ${nSpecies};`);
    m.push(`n_observables = ${groups.length};`);
    m.push(`n_ratelaws = ${nRxns};`);
    m.push('');

    // ODE solver options
    m.push('%% ODE solver options');
    let odesetArgs = `'RelTol', ${rtol}, 'AbsTol', ${atol}, 'Stats', '${stats ? 'on' : 'off'}', 'BDF', '${bdf ? 'on' : 'off'}', 'MaxOrder', ${maxOrder}`;
    if (maxStep > 0) {
      odesetArgs += `, 'MaxStep', ${maxStep}`;
    }
    m.push(`odeopts = odeset(${odesetArgs});`);
    m.push('');

    // Solve ODE
    m.push('%% Solve ODE');
    m.push('try');
    m.push('    [~, species_out] = ode15s(@(t,y) calc_species_deriv(t, y, parameters), timepoints, species_init, odeopts);');
    m.push('catch e');
    m.push('    err = 1;');
    m.push("    fprintf('Integration error: %s\\n', e.message);");
    m.push('    timepoints = [];');
    m.push('    species_out = [];');
    m.push('    observables_out = [];');
    m.push('    return;');
    m.push('end');
    m.push('');

    // Compute observables at each time point
    m.push('%% Compute observables at each time point');
    m.push('observables_out = zeros(length(timepoints), n_observables);');
    m.push('for t_idx = 1:length(timepoints)');
    m.push("    observables_out(t_idx, :) = calc_observables(species_out(t_idx, :)', parameters);");
    m.push('end');
    m.push('');

    // Plot results
    m.push('%% Plot results');
    m.push('if (~suppress_plot)');
    m.push('    figure;');
    if (groups.length > 0) {
      m.push('    plot(timepoints, observables_out);');
      const legendEntries = groups.map(g => `'${g.name}'`).join(', ');
      m.push(`    legend(${legendEntries}, 'Location', 'best');`);
      m.push("    ylabel('Number', 'FontSize', 12);");
    } else {
      m.push('    plot(timepoints, species_out);');
      m.push("    ylabel('Species Count', 'FontSize', 12);");
    }
    m.push("    xlabel('Time', 'FontSize', 12);");
    m.push(`    title('${model.name || 'Model'}', 'FontSize', 14);`);
    m.push('end');
    m.push('');

    m.push('err = 0;');
    m.push('return;');
    m.push('');

    // ===== Nested function: getDefaultParameters =====
    m.push('%% Default parameters');
    m.push('function p = getDefaultParameters()');
    m.push(`    p = zeros(${paramNames.length}, 1);`);
    for (let i = 0; i < paramNames.length; i++) {
      m.push(`    p(${i + 1}) = ${paramValues[i]}; % ${paramNames[i]}`);
    }
    m.push('end');
    m.push('');

    // ===== Nested function: getInitialSpecies =====
    m.push('%% Default initial species concentrations');
    m.push('function y0 = getInitialSpecies()');
    m.push(`    y0 = zeros(${nSpecies}, 1);`);
    for (let i = 0; i < nSpecies; i++) {
      const sp = species[i];
      m.push(`    y0(${i + 1}) = ${sp.initialConcentration}; % ${sp.name}`);
    }
    m.push('end');
    m.push('');

    // ===== Nested function: calc_expressions =====
    m.push('%% Calculate expressions from parameters');
    m.push('function expressions = calc_expressions(parameters)');
    m.push(`    expressions = zeros(${paramNames.length}, 1);`);
    for (let i = 0; i < paramNames.length; i++) {
      m.push(`    expressions(${i + 1}) = parameters(${i + 1}); % ${paramNames[i]}`);
    }
    m.push('end');
    m.push('');

    // ===== Nested function: calc_observables =====
    m.push('%% Calculate observables from species');
    m.push('function observables = calc_observables(species, parameters)');
    m.push(`    observables = zeros(${groups.length}, 1);`);
    for (let g = 0; g < groups.length; g++) {
      const group = groups[g];
      if (group.entries.length === 0) {
        m.push(`    observables(${g + 1}) = 0; % ${group.name}`);
      } else {
        const terms = group.entries.map(e => {
          return e.weight > 1
            ? `${e.weight}*species(${e.speciesIndex + 1})`
            : `species(${e.speciesIndex + 1})`;
        });
        m.push(`    observables(${g + 1}) = ${terms.join(' + ')}; % ${group.name}`);
      }
    }
    m.push('end');
    m.push('');

    // ===== Nested function: calc_ratelaws =====
    m.push('%% Calculate rate laws');
    m.push('function ratelaws = calc_ratelaws(species, expressions, observables)');
    m.push(`    ratelaws = zeros(${nRxns}, 1);`);
    for (let r = 0; r < nRxns; r++) {
      const rxn = reactions[r];
      let line = `    ratelaws(${r + 1}) = `;

      // Get rate constant / expression
      let rateStr = rxn.rate || String(rxn.rateConstant);
      // Strip |local: suffix if present
      const localPos = rateStr.indexOf('|local:');
      if (localPos !== -1) {
        rateStr = rateStr.substring(0, localPos);
      }

      const statFactor = rxn.statFactor ?? 1;

      // Try as numeric
      const rateVal = parseFloat(rateStr);
      if (!isNaN(rateVal) && String(rateVal) === rateStr.trim()) {
        // Purely numeric rate
        const combined = statFactor * rateVal;
        line += String(combined);
      } else {
        // Parameter reference or expression - convert to MATLAB
        const matlabRate = this.convertRateToMatlab(rateStr, paramNames);
        if (Math.abs(statFactor - 1.0) > 1e-12) {
          line += `${statFactor}*${matlabRate}`;
        } else {
          line += matlabRate;
        }
      }

      // Multiply by reactant concentrations
      // Reactants in the TS model are species names; we need indices
      for (const reactantName of rxn.reactants) {
        const idx = species.findIndex(s => s.name === reactantName);
        if (idx >= 0) {
          line += `*species(${idx + 1})`;
        }
      }

      line += ';';
      m.push(line);
    }
    m.push('end');
    m.push('');

    // ===== Nested function: calc_species_deriv =====
    m.push('%% Species derivative function');
    m.push('function Dspecies = calc_species_deriv(t, species, parameters)');
    m.push('    expressions = calc_expressions(parameters);');
    m.push('    observables = calc_observables(species, parameters);');
    m.push('    ratelaws = calc_ratelaws(species, expressions, observables);');
    m.push('');
    m.push(`    Dspecies = zeros(${nSpecies}, 1);`);
    m.push('');

    for (const entry of stoich) {
      if (fixedSpecies[entry.speciesIndex]) {
        m.push(`    Dspecies(${entry.speciesIndex + 1}) = 0; % fixed species`);
      } else if (entry.rxnCoeffs.length === 0) {
        continue;
      } else {
        let line = `    Dspecies(${entry.speciesIndex + 1}) = `;
        let first = true;
        for (const { rxnIndex, coeff } of entry.rxnCoeffs) {
          if (first) {
            if (coeff === 1) {
              line += `ratelaws(${rxnIndex + 1})`;
            } else if (coeff === -1) {
              line += `-ratelaws(${rxnIndex + 1})`;
            } else {
              line += `${coeff}*ratelaws(${rxnIndex + 1})`;
            }
          } else {
            if (coeff === 1) {
              line += ` + ratelaws(${rxnIndex + 1})`;
            } else if (coeff === -1) {
              line += ` - ratelaws(${rxnIndex + 1})`;
            } else if (coeff > 0) {
              line += ` + ${coeff}*ratelaws(${rxnIndex + 1})`;
            } else {
              line += ` - ${-coeff}*ratelaws(${rxnIndex + 1})`;
            }
          }
          first = false;
        }
        line += ';';
        m.push(line);
      }
    }

    m.push('end');
    m.push('');

    m.push('end % main function');
    m.push('');

    return m.join('\n');
  }

  /**
   * Convert a rate expression string to MATLAB syntax by replacing parameter
   * names with expressions(i) references.
   *
   * Replaces longest names first to prevent partial-match corruption.
   */
  private static convertRateToMatlab(rate: string, paramNames: string[]): string {
    let result = rate;

    // Sort by name length descending to prevent partial matches
    const sorted = paramNames
      .map((name, i) => ({ name, index: i }))
      .sort((a, b) => b.name.length - a.name.length);

    for (const { name, index } of sorted) {
      const paramRef = `expressions(${index + 1})`;
      let pos = 0;
      while (true) {
        const found = result.indexOf(name, pos);
        if (found === -1) break;

        const validStart = found === 0 || !/[A-Za-z0-9_]/.test(result[found - 1]);
        const endPos = found + name.length;
        const validEnd = endPos >= result.length || !/[A-Za-z0-9_]/.test(result[endPos]);

        if (validStart && validEnd) {
          result = result.substring(0, found) + paramRef + result.substring(endPos);
          pos = found + paramRef.length;
        } else {
          pos = found + name.length;
        }
      }
    }

    return result;
  }

  /**
   * Build observable groups by matching observable patterns against species.
   *
   * Uses the concreteObservables from network expansion when available (preferred),
   * otherwise falls back to simple name-based matching.
   */
  private static computeObservableGroups(
    model: BNGLModel,
    species: BNGLModel['species'],
  ): ObservableGroup[] {
    const groups: ObservableGroup[] = [];
    const observables = model.observables ?? [];

    // Check for pre-computed concrete observables (from NetworkExpansion)
    const concreteObs = (model as any).concreteObservables as
      | Array<{ name: string; type: string; indices: number[]; coefficients: number[]; volumes: number[] }>
      | undefined;

    if (concreteObs && concreteObs.length > 0) {
      for (const obs of concreteObs) {
        const group: ObservableGroup = { name: obs.name, entries: [] };
        for (let j = 0; j < obs.indices.length; j++) {
          group.entries.push({
            speciesIndex: obs.indices[j],
            weight: obs.coefficients[j],
          });
        }
        groups.push(group);
      }
      return groups;
    }

    // Fallback: use model observables with simple pattern matching
    for (const obs of observables) {
      const group: ObservableGroup = { name: obs.name, entries: [] };

      // Simple substring/exact pattern matching
      // Optimized string split to prevent intermediate array allocations
      const patterns: string[] = [];
      const str = obs.pattern || '';
      let start = 0;
      const len = str.length;
      while (start < len) {
        let end = str.indexOf(',', start);
        if (end === -1) end = len;
        const part = str.substring(start, end).trim();
        if (part) {
          patterns.push(part);
        }
        start = end + 1;
      }

      for (let i = 0; i < species.length; i++) {
        const speciesName = species[i].name;
        let weight = 0;

        for (const pat of patterns) {
          if (obs.type === 'species' || obs.type === 'Species') {
            // Species observable: count 1 if pattern matches
            if (speciesName.includes(pat) || speciesName === pat) {
              weight = 1;
              break;
            }
          } else {
            // Molecules observable: count occurrences
            let idx = 0;
            let count = 0;
            while (true) {
              const pos = speciesName.indexOf(pat, idx);
              if (pos === -1) break;
              count++;
              idx = pos + 1;
            }
            weight += count;
          }
        }

        if (weight > 0) {
          group.entries.push({ speciesIndex: i, weight });
        }
      }

      groups.push(group);
    }

    return groups;
  }

  /**
   * Compute the stoichiometry matrix from reactions and species.
   * For each species, produces a list of (reaction, net coefficient) pairs.
   */
  private static computeStoichiometryFromSpecies(
    reactions: BNGLReaction[],
    species: BNGLModel['species'],
  ): StoichEntry[] {
    const nameToIndex = new Map<string, number>();
    for (let i = 0; i < species.length; i++) {
      nameToIndex.set(species[i].name, i);
    }

    const stoichMap = new Map<number, Map<number, number>>();

    for (let r = 0; r < reactions.length; r++) {
      const rxn = reactions[r];
      for (const reactant of rxn.reactants) {
        const idx = nameToIndex.get(reactant);
        if (idx === undefined) continue;
        if (!stoichMap.has(idx)) stoichMap.set(idx, new Map());
        const rxnMap = stoichMap.get(idx)!;
        rxnMap.set(r, (rxnMap.get(r) ?? 0) - 1);
      }
      for (let pi = 0; pi < rxn.products.length; pi++) {
        const product = rxn.products[pi];
        const idx = nameToIndex.get(product);
        if (idx === undefined) continue;
        const productStoich = rxn.productStoichiometries?.[pi] ?? 1;
        if (!stoichMap.has(idx)) stoichMap.set(idx, new Map());
        const rxnMap = stoichMap.get(idx)!;
        rxnMap.set(r, (rxnMap.get(r) ?? 0) + productStoich);
      }
    }

    const result: StoichEntry[] = [];
    const sortedSpeciesIndices = Array.from(stoichMap.keys()).sort((a, b) => a - b);
    for (const specIdx of sortedSpeciesIndices) {
      const rxnMap = stoichMap.get(specIdx)!;
      const coeffs: Array<{ rxnIndex: number; coeff: number }> = [];
      const sortedRxns = Array.from(rxnMap.entries()).sort((a, b) => a[0] - b[0]);
      for (const [rxnIdx, coeff] of sortedRxns) {
        if (coeff !== 0) {
          coeffs.push({ rxnIndex: rxnIdx, coeff });
        }
      }
      if (coeffs.length > 0) {
        result.push({ speciesIndex: specIdx, rxnCoeffs: coeffs });
      }
    }

    return result;
  }
}
