/**
 * spatialReflectRng.spec.ts — boundary reflection and RNG correctness.
 *
 * Covers three consumer-visible defects in the live spatial path
 * (components/SpatialPanel -> spatialService -> spatialWorker -> SpatialSimulation):
 *
 * C3  reflectCoord folded with `while` and hung forever for zero-width extents
 *     and for ±Infinity coordinates (which gaussian() could produce, see C4).
 * C4  Box-Muller drew u1 from [0, 1); u1 === 0 gives log(0) = -Infinity.
 * C5  xoshiro256** used unbounded BigInt arithmetic, so bits above bit 63 leaked
 *     into the SplitMix64 seeding and the scrambler: the stream was not
 *     xoshiro256**. The seeder is now canonical SplitMix64 (counter kept
 *     separate from the scrambled word), which both engines implement.
 */

import { describe, it, expect } from 'vitest';
import {
  reflectCoord,
  validateCompartmentGeometries,
  Xoshiro256StarStar,
  SpatialSimulation,
} from '../src/services/spatial/SpatialSimulation';
import type { CompartmentGeometry } from '../src/services/spatial/SpatialConfig';

describe('reflectCoord', () => {
  // Each test gets a short timeout: the pre-fix implementation looped forever
  // on these inputs, which is exactly the regression being guarded.
  const NO_HANG = 2000;

  it('terminates and returns min for a zero-width extent', { timeout: NO_HANG }, () => {
    expect(reflectCoord(1, 0, 0)).toBe(0);
    expect(reflectCoord(-1, 5, 5)).toBe(5);
    expect(reflectCoord(0, 0, 0)).toBe(0);
  });

  it('terminates and returns a finite value for non-finite coordinates', { timeout: NO_HANG }, () => {
    for (const x of [Infinity, -Infinity, NaN]) {
      const folded = reflectCoord(x, 0, 1);
      expect(Number.isFinite(folded)).toBe(true);
      // Documented convention: collapse to the lower bound.
      expect(folded).toBe(0);
      expect(reflectCoord(x, -2, 3)).toBe(-2);
    }
  });

  it('returns min when the interval is inverted or non-finite', () => {
    expect(reflectCoord(5, 10, 0)).toBe(10);
    expect(reflectCoord(5, 0, Number.NaN)).toBe(0);
    expect(reflectCoord(5, -Infinity, Infinity)).toBe(-Infinity);
  });

  it('mirrors into [min, max]', () => {
    expect(reflectCoord(2.3, 0, 1)).toBeCloseTo(0.3, 12);
    expect(reflectCoord(-0.2, 0, 1)).toBeCloseTo(0.2, 12);
    expect(reflectCoord(0.5, 0, 1)).toBeCloseTo(0.5, 12);
    expect(reflectCoord(1.5, 0, 1)).toBeCloseTo(0.5, 12);
    expect(reflectCoord(2.7, 0, 1)).toBeCloseTo(0.7, 12);
    // Interior points are untouched.
    expect(reflectCoord(0, 0, 1)).toBe(0);
    expect(reflectCoord(1, 0, 1)).toBe(1);
    expect(reflectCoord(0.25, 0, 1)).toBe(0.25);
    // Offset interval.
    expect(reflectCoord(11.4, 10, 11)).toBeCloseTo(10.6, 12);
  });

  it('always lands inside the interval, however far out of range', () => {
    for (const x of [1e3, -1e3, 1e12, -1e12, 1e18, -1e18, 123456.789]) {
      const folded = reflectCoord(x, -1.5, 2.5);
      expect(folded).toBeGreaterThanOrEqual(-1.5);
      expect(folded).toBeLessThanOrEqual(2.5);
    }
  });

  it('is periodic with period 2*(max-min) and symmetric about min', () => {
    const min = -1.5;
    const max = 2.5;
    const w = max - min;
    for (const x of [0, 0.3, 1.7, 4.2, -9.1, 123.456]) {
      const folded = reflectCoord(x, min, max);
      expect(reflectCoord(x + 2 * w, min, max)).toBeCloseTo(folded, 9);
      // The fold is symmetric about `min`: folding the mirrored point gives the
      // same result.
      expect(reflectCoord(2 * min - x, min, max)).toBeCloseTo(folded, 9);
    }
  });
});

describe('Xoshiro256StarStar', () => {
  // Reference vectors for xoshiro256** with CANONICAL SplitMix64 seeding
  // (counter advancing separately from the scrambled word), generated by
  // compiling a standalone C reference natively with both clang and gcc, which
  // produced identical output:
  //
  //   uint64_t x = seed; for (i<4) { x += 0x9e3779b97f4a7c15; uint64_t z = x;
  //     z = (z^(z>>30))*0xbf58476d1ce4e5b9; z = (z^(z>>27))*0x94d049bb133111eb;
  //     s[i] = z ^ (z>>31); }
  //   // then result = rotl(s[1]*5, 7) * 9 with the standard xoshiro256** update
  //
  //   clang -O2 -o canon canon.c && ./canon
  //
  // The same harness reproduces the published xoshiro256** known-answer
  // sequence for the unseeded state {1,2,3,4}:
  //   11520, 0, 1509978240, 1215971899390074240, 1216172134540287360
  // which pins the `next()` scrambler independently of the seeder.
  //
  // These are NOT self-referential: the pre-fix TypeScript produces a different
  // stream (its BigInt arithmetic was never masked to 64 bits), so this test
  // fails on the unfixed code — see the PR description.
  const REFERENCE_VECTORS: Record<number, bigint[]> = {
    0: [
      0x99ec5f36cb75f2b4n, 0xbf6e1f784956452an, 0x1a5f849d4933e6e0n, 0x6aa594f1262d2d2cn,
      0xbba5ad4a1f842e59n, 0xffef8375d9ebcacan, 0x6c160deed2f54c98n, 0x8920ad648fc30a3fn,
      0xdb032c0ba7539731n, 0xeb3a475a3e749a3dn,
    ],
    1: [
      0xb3f2af6d0fc710c5n, 0x853b559647364cean, 0x92f89756082a4514n, 0x642e1c7bc266a3a7n,
      0xb27a48e29a233673n, 0x24c123126ffda722n, 0x123004ef8df510e6n, 0x61954dcc47b1e89dn,
      0xddfdb48ab9ed4a21n, 0x8d3cdb8c3aa5b1d0n,
    ],
    12345: [
      0xbe6a36374160d49bn, 0x214aaa0637a688c6n, 0xf69d16de9954d388n, 0x0c60048c4e96e033n,
      0x8e2076aeed51c648n, 0x02bbcc1c1fc50f84n, 0x28e72a4fec84f699n, 0x4bb9d7cbb8dddeben,
      0x62cea6a22cf0bd36n, 0xe91df042ccde955dn,
    ],
  };

  for (const [seed, expected] of Object.entries(REFERENCE_VECTORS)) {
    it(`matches reference xoshiro256** for seed ${seed}`, () => {
      const rng = new Xoshiro256StarStar(Number(seed));
      const actual = Array.from({ length: expected.length }, () => rng.next());
      expect(actual).toEqual(expected);
    });
  }

  it('produces reproducible streams for equal seeds and distinct streams for distinct seeds', () => {
    const draw = (seed: number): bigint[] => {
      const rng = new Xoshiro256StarStar(seed);
      return Array.from({ length: 20 }, () => rng.next());
    };
    expect(draw(7)).toEqual(draw(7));
    expect(draw(7)).not.toEqual(draw(8));
  });

  it('maps next() to doubles in [0, 1)', () => {
    const rng = new Xoshiro256StarStar(42);
    for (let i = 0; i < 20000; i++) {
      const u = rng.random();
      expect(u).toBeGreaterThanOrEqual(0);
      expect(u).toBeLessThan(1);
    }
  });

  it('emits 64-bit outputs only', () => {
    const rng = new Xoshiro256StarStar(99);
    const mask = 0xFFFFFFFFFFFFFFFFn;
    for (let i = 0; i < 500; i++) {
      const v = rng.next();
      expect(v).toBeGreaterThanOrEqual(0n);
      expect(v & ~mask).toBe(0n);
    }
  });

  it('never returns Infinity or NaN from gaussian()', () => {
    const rng = new Xoshiro256StarStar(2024);
    let sum = 0;
    let sumSq = 0;
    const n = 100000;
    for (let i = 0; i < n; i++) {
      const g = rng.gaussian();
      expect(Number.isFinite(g)).toBe(true);
      sum += g;
      sumSq += g * g;
    }
    const mean = sum / n;
    const variance = sumSq / n - mean * mean;
    expect(Math.abs(mean)).toBeLessThan(0.02);
    expect(Math.abs(variance - 1)).toBeLessThan(0.02);
  });

  it('stays finite when random() returns exactly 0 (log(0) = -Infinity pre-fix)', () => {
    // Force the 2^-53 event where the uniform draw is 0, so u1 = 1 - 0 = 1.
    class ZeroFirstDraw extends Xoshiro256StarStar {
      private calls = 0;

      constructor(seed: number, private readonly second: number) {
        super(seed);
      }

      override random(): number {
        return this.calls++ === 0 ? 0 : this.second;
      }
    }

    const degenerate = new ZeroFirstDraw(5, 0.5).gaussian();
    expect(Number.isFinite(degenerate)).toBe(true);
    expect(degenerate).toBe(0);

    const mixed = new ZeroFirstDraw(5, 0.25).gaussian();
    expect(Number.isFinite(mixed)).toBe(true);
  });
});

describe('SpatialSimulation geometry validation', () => {
  const bngl = (size: string): string => `
begin compartments
  EC 3 ${size}
end compartments

begin parameters
  k1 0.5
end parameters

begin species
  A() 10
  B() 10
end species

begin reaction rules
  A() -> B() k1
end reaction rules
`;

  it('rejects a zero-thickness compartment at initialize instead of hanging', async () => {
    const sim = new SpatialSimulation({ dt: 1e-6, tEnd: 1e-3, seed: 1 });
    await expect(sim.initialize(bngl('0'))).rejects.toThrow(/Invalid spatial geometry for compartment "EC"/);
    await expect(sim.initialize(bngl('0'))).rejects.toThrow(/radius must be a finite positive number \(got 0\)/);
  });

  it('rejects a negative compartment size (NaN radius)', async () => {
    const sim = new SpatialSimulation();
    await expect(sim.initialize(bngl('-5'))).rejects.toThrow(/Invalid spatial geometry/);
  });

  it('accepts a well-formed compartment', async () => {
    const sim = new SpatialSimulation({ dt: 1e-6, tEnd: 1e-3, seed: 1 });
    await expect(sim.initialize(bngl('1000'))).resolves.toBeUndefined();
    const geoms = sim.getGeometries();
    expect(geoms).toHaveLength(1);
    expect(geoms[0].radius).toBeGreaterThan(0);
  });

  it('rejects box geometries with a zero or negative half-extent', () => {
    const box = (name: string, halfExtents: [number, number, number]): CompartmentGeometry => ({
      compartmentId: 0,
      name,
      dimension: 3,
      volume: 8,
      parentId: null,
      shape: 'box',
      center: [0, 0, 0],
      halfExtents,
    });

    expect(() => validateCompartmentGeometries([box('FlatBox', [1, 0, 1])])).toThrow(
      /half-extent must be a finite positive number \(got 0\)/
    );
    expect(() => validateCompartmentGeometries([box('InvertedBox', [1, -1, 1])])).toThrow(
      /Invalid spatial geometry for compartment "InvertedBox"/
    );
    expect(() => validateCompartmentGeometries([box('Fine', [1, 1, 1])])).not.toThrow();
  });
});