/**
 * BNGLWriter.ts - Serializes BNGLModel back to .bngl format
 *
 * Implements the writeModel/writeBNGL actions from BNG2.
 * Outputs all model blocks in standard BNGL format.
 *
 * Reference: BNG2/bng2/Perl2/BNGOutput.pm::writeModel()
 */

import type { BNGLModel } from '../../types';

export interface BNGLWriterOptions {
  includeComments?: boolean;
  includeActions?: boolean;
  overwriteAction?: boolean;
  generatedBy?: string;
}

/**
 * Serialize a BNGLModel to .bngl format
 * @param model The model to serialize
 * @param options Writer options
 * @returns BNGL-formatted string
 */
export function writeBNGL(model: BNGLModel, options: BNGLWriterOptions = {}): string {
  let output = '';

  output += writeHeaderBlock(options);
  output += writeModelNameBlock(model);
  output += writeParametersBlock(model);
  output += writeCompartmentsBlock(model);
  output += writeMoleculeTypesBlock(model, options);
  output += writeSpeciesBlock(model);
  output += writeObservablesBlock(model, options);
  output += writeFunctionsBlock(model);
  output += writeReactionRulesBlock(model, options);
  output += writePopulationMapsBlock(model);
  output += writePopulationTypesBlock(model);
  output += writeReactionsBlock(model);

  // Note: BNG2 places "end model" before "begin actions"
  output += 'end model\n';

  output += writeActionsBlock(model, options);

  return output;
}

/**
 * Format a number for BNGL output
 */
function formatNumber(value: number): string {
  if (!Number.isFinite(value)) return '0';

  // Use scientific notation for very large or very small numbers
  if (Math.abs(value) > 1e6 || (Math.abs(value) < 1e-3 && value !== 0)) {
    return value.toExponential();
  }

  // For normal-sized numbers, use fixed notation
  const str = value.toString();
  // Remove unnecessary trailing zeros after decimal point
  return str.replace(/(\.\d*?[1-9])0+$/, '$1').replace(/\.0+$/, '');
}

/**
 * Format action arguments for BNGL output
 */
function formatActionArgs(args: Record<string, any>): string {
  const pairs: string[] = [];
  for (const [key, value] of Object.entries(args)) {
    if (typeof value === 'string') {
      pairs.push(`${key}=>"${value}"`);
    } else if (typeof value === 'number') {
      pairs.push(`${key}=>${formatNumber(value)}`);
    } else if (typeof value === 'boolean') {
      pairs.push(`${key}=>${value ? '1' : '0'}`);
    } else {
      pairs.push(`${key}=>"${String(value)}"`);
    }
  }
  return pairs.join(', ');
}

/**
 * Write a model to a .bngl file
 * @param model The model to write
 * @param filepath Output file path
 * @param options Writer options
 * @returns Promise that resolves when file is written
 */
export async function writeBNGLFile(_model: BNGLModel, _filepath: string, _options: BNGLWriterOptions = {}): Promise<void> {
  // writeBNGL(model, options);
  // This is a placeholder - actual implementation depends on runtime environment
  // In Node.js, use fs.writeFileSync; in browser, trigger download
  throw new Error(
    'writeBNGLFile (direct file writing) is not available in this environment. ' +
    'Use writeBNGL(model, options) to get the BNGL content as a string, then write it yourself. ' +
    'In the browser, use the export/download feature in the UI instead.'
  );
}


function writeHeaderBlock(options: BNGLWriterOptions): string {
  const { includeComments = true, generatedBy = 'BioNetGen Web Simulator' } = options;
  let output = '';
  if (includeComments) {
    output += `# Generated by ${generatedBy}\n`;
    output += `# ${new Date().toISOString()}\n\n`;
  }
  return output;
}

function writeModelNameBlock(model: BNGLModel): string {
  let output = `begin model\n`;
  if (model.name) {
    output += `# Model: ${model.name}\n`;
  }
  output += '\n';
  return output;
}

function writeParametersBlock(model: BNGLModel): string {
  if (Object.keys(model.parameters).length === 0) return '';
  let output = 'begin parameters\n';
  for (const [name, value] of Object.entries(model.parameters).sort((a, b) => a[0].localeCompare(b[0]))) {
    output += `  ${name} ${formatNumber(value)}\n`;
  }
  output += 'end parameters\n\n';
  return output;
}

function writeCompartmentsBlock(model: BNGLModel): string {
  if (!model.compartments || model.compartments.length === 0) return '';
  let output = 'begin compartments\n';
  for (const comp of model.compartments) {
    let line = `  ${comp.name} ${comp.dimension} ${formatNumber(comp.size)}`;
    if (comp.parent) {
      line += ` ${comp.parent}`;
    }
    output += line + '\n';
  }
  output += 'end compartments\n\n';
  return output;
}

function writeMoleculeTypesBlock(model: BNGLModel, options: BNGLWriterOptions): string {
  if (!model.moleculeTypes || model.moleculeTypes.length === 0) return '';
  const { includeComments = true } = options;
  let output = 'begin molecule types\n';
  for (const mt of model.moleculeTypes) {
    const components = mt.components && mt.components.length > 0
      ? `(${mt.components.join(',')})`
      : '()';
    output += `  ${mt.name}${components}`;
    if (includeComments && mt.comment) {
      output += ` # ${mt.comment}`;
    }
    output += '\n';
  }
  output += 'end molecule types\n\n';
  return output;
}

function writeSpeciesBlock(model: BNGLModel): string {
  if (!model.species || model.species.length === 0) return '';
  let output = 'begin species\n';
  for (const sp of model.species) {
    let line = `  ${sp.name} ${formatNumber(sp.initialConcentration)}`;
    if (sp.isConstant) {
      line += ' $ # Constant';
    }
    output += line + '\n';
  }
  output += 'end species\n\n';
  return output;
}

function writeObservablesBlock(model: BNGLModel, options: BNGLWriterOptions): string {
  if (!model.observables || model.observables.length === 0) return '';
  const { includeComments = true } = options;
  let output = 'begin observables\n';
  for (const obs of model.observables) {
    const type = obs.type.charAt(0).toUpperCase() + obs.type.slice(1); // Capitalize
    output += `  ${type} ${obs.name} ${obs.pattern}`;
    if (includeComments && obs.comment) {
      output += ` # ${obs.comment}`;
    }
    output += '\n';
  }
  output += 'end observables\n\n';
  return output;
}

function writeFunctionsBlock(model: BNGLModel): string {
  if (!model.functions || model.functions.length === 0) return '';
  let output = 'begin functions\n';
  for (const fn of model.functions) {
    const args = fn.args.length > 0 ? fn.args.join(',') : '';
    output += `  ${fn.name}(${args}) = ${fn.expression}\n`;
  }
  output += 'end functions\n\n';
  return output;
}

function writeReactionRulesBlock(model: BNGLModel, options: BNGLWriterOptions): string {
  if (!model.reactionRules || model.reactionRules.length === 0) return '';
  const { includeComments = true } = options;
  let output = 'begin reaction rules\n';
  for (const rule of model.reactionRules) {
    let line = '  ';
    if (rule.name) {
      line += `${rule.name}: `;
    }

    // Reactants
    line += rule.reactants.join(' + ');

    // Arrow
    if (rule.isBidirectional && rule.reverseRate) {
      line += ' <-> ';
    } else {
      line += ' -> ';
    }

    // Products
    line += rule.products.join(' + ');

    // Rate(s)
    line += ` ${rule.rate}`;
    if (rule.isBidirectional && rule.reverseRate) {
      line += `, ${rule.reverseRate}`;
    }

    // Modifiers
    const modifiers: string[] = [];
    if (rule.deleteMolecules) modifiers.push('DeleteMolecules');
    if (rule.moveConnected) modifiers.push('MoveConnected');
    if (rule.matchOnce) modifiers.push('MatchOnce');
    if (!rule.allowsIntramolecular) modifiers.push('exclude_intramolecular');

    if (modifiers.length > 0) {
      line += ` ${modifiers.join(', ')}`;
    }

    // Constraints
    if (rule.constraints && rule.constraints.length > 0) {
      for (const constraint of rule.constraints) {
        line += ` ${constraint}`;
      }
    }

    if (includeComments && rule.comment) {
      line += ` # ${rule.comment}`;
    }

    output += line + '\n';
  }
  output += 'end reaction rules\n\n';
  return output;
}

function writePopulationMapsBlock(model: BNGLModel): string {
  if (!model.populationMaps || model.populationMaps.length === 0) return '';
  let output = 'begin population maps\n';
  for (const pm of model.populationMaps) {
    output += `  ${pm.pattern} -> ${pm.populationName}()`;
    if (pm.lumpingRate && pm.lumpingRate !== '0') {
       output += ` ${pm.lumpingRate}`;
    }
    output += '\n';
  }
  output += 'end population maps\n\n';
  return output;
}

function writePopulationTypesBlock(model: BNGLModel): string {
  if (!model.populationTypes || model.populationTypes.length === 0) return '';
  let output = 'begin population types\n';
  for (const pt of model.populationTypes) {
     const components = pt.components && pt.components.length > 0
      ? `(${pt.components.join(',')})`
      : '()';
    output += `  ${pt.name}${components}\n`;
  }
  output += 'end population types\n\n';
  return output;
}

function writeReactionsBlock(model: BNGLModel): string {
  if (!model.reactions || model.reactions.length === 0) return '';
  let output = 'begin reactions\n';
  for (const rxn of model.reactions) {
    let line = '  ';
    if (rxn.name) {
      line += `${rxn.name}: `;
    }

    line += rxn.reactants.join(' + ');
    line += ' -> ';
    line += rxn.products.join(' + ');
    line += ` ${rxn.rate}`;

    output += line + '\n';
  }
  output += 'end reactions\n\n';
  return output;
}

function writeActionsBlock(model: BNGLModel, options: BNGLWriterOptions): string {
  const { includeActions = false, overwriteAction = true } = options;
  if (!includeActions) return '';

  let output = '\nbegin actions\n';
  if (model.actions && model.actions.length > 0) {
    for (const action of model.actions) {
      output += `  ${action.type}(${formatActionArgs(action.args)})\n`;
    }
  } else {
    // Add default actions
    if (overwriteAction) {
      output += '  generate_network({overwrite=>1})\n';
    } else {
      output += '  generate_network()\n';
    }
    output += '  simulate({method=>"ode", t_end=>100, n_steps=>100})\n';
  }
  output += 'end actions\n';
  return output;
}
